version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: "caddy"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./caddy/data:/data
      - ./caddy/key.pem:/etc/ssl/private/key.pem
      - ./caddy/certificate.pem:/etc/ssl/certs/certificate.pem
    networks:
      - traefik

networks:
  traefik:
    external: true
