version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: "caddy2"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./caddy/data:/data
      - ./caddy/key.pem:/etc/ssl/private/key.pem
      - ./caddy/certificate.pem:/etc/ssl/certs/certificate.pem
    networks:
      - ilikefike-int
      - ilikefike-ext

networks:
  ilikefike-ext:
    external: true
  ilikefike-int:
    external: false
    driver: bridge
