version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: "caddy"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./caddy/data:/data
      - ./caddy/key.pem:/etc/ssl/private/key.pem
      - ./caddy/certificate.pem:/etc/ssl/certs/certificate.pem
    networks:
      - ilikefike-int
      - ilikefike-ext
  whoami:
    image: traefik/whoami
    container_name: "whoami"
    command:
      - --port=2001
    networks:
      - ilikefike-int
  db:
    image: mariadb:latest
    container_name: "db"
    restart: always
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    volumes:
      - ./mariadb/datadir:/var/lib/mysql
    networks:
      - ilikefike-int
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    networks:
      - ilikefike-int

networks:
  ilikefike-ext:
    external: true
  ilikefike-int:
    external: false
    driver: bridge
