version: '3'

services:

  traefik:
    container_name: traefik
    image: traefik:v2.2
    restart: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.ilikefike.com"
      - "traefik.port=8080"

  whoami:
    container_name: whoami
    image: containous/whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.ilikefike.com"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
