version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/caddyfile:/etc/caddy/Caddyfile
    networks:
      - traefik

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    networks:
      - traefik

networks:
  traefik:
    external: true
