version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: "caddy"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./caddy/data:/data
      - ./caddy/key.pem:/etc/ssl/private/key.pem
      - ./caddy/certificate.pem:/etc/ssl/certs/certificate.pem
    networks:
      - ilikefike-int
      - ilikefike-ext
  whoami:
    image: traefik/whoami
    container_name: "whoami"
    command:
      - --port=2001
    networks:
      - ilikefike-int
  db:
    image: mariadb:11.1.2-jammy
    container_name: "db"
    restart: always
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    volumes:
      - ./mariadb/datadir:/var/lib/mysql
    networks:
      - ilikefike-int
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=${DB_USER}
  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    networks:
      - ilikefike-int
  nextcloud:
    image: nextcloud
    container_name: "nextcloud"
    restart: always
    links:
      - db
    networks:
      - ilikefike-int
    volumes:
      - ./nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=db

networks:
  ilikefike-ext:
    external: true
  ilikefike-int:
    external: false
    driver: bridge
