logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.api]
    address = ":8080"
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]
  entryPoint = "api"
  dashboard = true

[acme]
  email = "ilikefike@fikeweb.com"
  storage = "acme.json"
  entryPoint = "https"
  acmeLogging = true
  onDemand = false
  onHostRule = true
[acme.httpChallenge]
  entryPoint = "http"

[docker]
  domain = "ilikefike.com"
  watch = true
  network = "traefik"
# expose containers explicitly (use the lable "traefik.enable=true" in your docker-compose)
  exposedbydefault = false